export const products = [
  {
    manufacturer: "Meditech",
    form: "Oral",
    molecule: "Anadrol (Oxymethalone)",
    concentration: "50mg",
    volume: "50mg",
    recommendedDosage: "1 tablet per day",
    productDescription:
      "The hormone Oxymethalone is an anabolic hormone that is taken orally. It is considered a synthetic hormone similar to testosterone in it's functions, so it is known as synthetic testosterone. It belongs to the category of androgens and anabolic steroids. It is used in treating anemia resulting from Undergoing Chemotherapy in cancer patients which results in a decrease of red blood cells in the body, it is also used in the treatment of osteoperosis and decreased muscle tissue in AIDS, where it stimulates growth of the muscles in the body. Oxymetholone falls under the commercial name of the drug, Anapaolone, Anadrol.",
    price: 160,
    image: "/products/product_images/Anadrol_Oxymethalone.webp",
    id: 1,
  },
  {
    manufacturer: "Meditech",
    form: "Oral",
    molecule: "Anavar (Oxandrolone)",
    concentration: "1Omg",
    volume: "10mg",
    recommendedDosage: "20-40mg/day",
    productDescription:
      "Anavar or Oxandrolone is an oral anabolic steroid derived from dihydronetestosterone, well designed to enhance strength and achieve high gains in muscle tissue without major side effects.",
    price: 145,
    image: "/products/product_images/Anavar_Oxandrolone.webp",
    id: 2,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Boldenone Undecylenate 250",
    concentration: "250mg/ml",
    volume: "10ml",
    recommendedDosage: "200-800mg/week",
    productDescription:
      "Also known as Equipoise, the Boldenone is a steroid highly valued by fundamental athletes. It provides exceptional gains while being very safe. The Boldenone is appreciated for a mass gain also because it provides an impressive muscular curve.",
    price: 95,
    image: "/products/product_images/Boldenone_Undecylenate_250.webp",
    id: 3,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Boldenone Undecylenate 400",
    concentration: "400mg/ml",
    volume: "10ml",
    recommendedDosage: "200-800mg/week",
    productDescription:
      "Also known as Equipoise, the Boldenone is a steroid highly valued by fundamental athletes. It provides exceptional gains while being very safe. The Boldenone is appreciated for a mass gain also because it provides an impressive muscular curve.",
    price: 145,
    image: "/products/product_images/Boldenone_Undecylenate_400.webp",
    id: 4,
  },
  {
    manufacturer: "Meditech",
    form: "Oral",
    molecule: "Clenbuterol",
    concentration: "40mg",
    volume: "40mg",
    recommendedDosage: "40mm grams per day",
    productDescription:
      "Clenbuterol is considered one of the effective products that help in losing and burning fat significantly. Clenbuterol is very popular for burning fat and losing weight. Clenbuterol is well known in the field of bodybuilding because of Clenbuterol's great effectiveness in losing fat and reaching the maximum degree of drying. This is why it is used during periods of slimming and drying because it helps a lot.",
    price: 88,
    image: "/products/product_images/Clenbuterol.webp",
    id: 5,
  },
  {
    manufacturer: "Meditech",
    form: "Oral",
    molecule: "Dianabol (Metandienone)",
    concentration: "10mm gr",
    volume: "10mm gr",
    recommendedDosage: "20-40mg/day",
    productDescription:
      "Dianabol is considered one of the most important hormones. Taken by athletes and bodybuilders in general, the Dianabol hormone is an important hormone that helps in buildling body muscles, gaining weight, and strengthening various muscles. In addition to increasing muscle mass within a short period of time, this is granted the muscle hormone also contains a huge amount of nitrogen which is the secret of its great ability to build muscles.",
    price: 95,
    image: "/products/product_images/Dianabol_Metandienone.webp",
    id: 6,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Drostanolone Enanthate",
    concentration: "200mg/ml",
    volume: "10ml",
    recommendedDosage: "200-600mg/week",
    productDescription:
      'The most effective and the most famous "finisher". The Drostanolone molecule of Masteron is an ideal product in many treatments. Not very interesting if taken alone. Take it to finalize you slimming or lean mass gain.',
    price: 140,
    image: "/products/product_images/Drostanolone_Enanthate.webp",
    id: 7,
  },
  {
    manufacturer: "Meditech",
    form: "Oral",
    molecule: "Halotestin (Fluoxymesterone)",
    concentration: "10mg",
    volume: "10mg",
    recommendedDosage: "20-40mg/day",
    productDescription:
      "The hormone Halotestin is considered one of the most important hormones in the world of body and muscle building. The hormone Halotestin is one of the derivatives of methyltestosterone, and it is a group of hormones that turn into a male hormone after taking it. It turns into a more androgenic compound, and it is important for people interested in the field of sports and the field of bodybuilding, and weight lifting in particular, in addition to sometimes prescribing it to some patients, it is resorted to in different ways, according to the intended purpose of taking it.",
    price: 170,
    image: "/products/product_images/Halotestin_Fluoxymesterone.webp",
    id: 8,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Masteron Drostanolone Propionate",
    concentration: "100mg/ml",
    volume: "10ml",
    recommendedDosage: "200-600mg/week",
    productDescription:
      "Introducing Masteron Drostanolone Propionate, which are procured from the most reliable sources in the market. It is an androgenic steroid that is used in the treatment of breast cancer. This injection can be avail by our clients within stipulated time frame.",
    price: 130,
    image: "/products/product_images/Masteron_Drostanolone_Propionate.webp",
    id: 9,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Methenolone Enanthate",
    concentration: "100mg/ml",
    volume: "10ml",
    recommendedDosage: "200-600mg/week",
    productDescription:
      "Methenolone, in its injectable form, stands as a potent anabolic steroid designed for muscle development. Leveraging a 1-methyl group to boost injectable bioavailability, Methenolone Acetate is fortified with a structural double bond, enhancing hepatic resistance. This injectable variant ensures sustained effectiveness, making it a valuable asset in your muscle-building endeavors.",
    price: 139,
    image: "/products/product_images/Methenolone_Enanthate.webp",
    id: 10,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Nandrolone Decanoate 250",
    concentration: "250mg/ml",
    volume: "10ml",
    recommendedDosage: "100-700mg/week",
    productDescription:
      "Deca-Durabolin Nandrolone is one of the main steroids taken by bodybuilders. Deca-Durabolin Nandrolone is the second largest injectable anabolic steroid after the testosterone. All steroid beginner and experienced users believe and have repeatedly admitted that Deca must be taken to get the best results from the use of steroids.",
    price: 98,
    image: "/products/product_images/Nandrolone_Decanoate_250.webp",
    id: 11,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Nandrolone Decanoate 400",
    concentration: "400mg/ml",
    volume: "10ml",
    recommendedDosage: "400-1200mg/week",
    productDescription:
      "Deca-Durabolin Nandrolone is one of the main steroids taken by bodybuilders. Deca-Durabolin Nandrolone is the second largest injectable anabolic steroid after the testosterone. All steroid beginner and experienced users believe and have repeatedly admitted that Deca must be taken to get the best results from the use of steroids.",
    price: 120,
    image: "/products/product_images/Nandrolone_Decanoate_400.webp",
    id: 12,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Nandrolone Phenylpropionate NPP",
    concentration: "100mg/ml",
    volume: "10ml",
    recommendedDosage: "200-400mg/week",
    productDescription:
      "Anabolic steroid with an enhanced anabolic and a reduced androgenic activity. The drug is used by athletes for muscle growth, appetite stimulation, increased red blood cell production and bone density. It increases protein synthesis in muscle cells and helps to achieve a positive nitrogen balance",
    price: 98,
    image: "/products/product_images/Nandrolone_Phenylpropionate_NPP.png",
    id: 13,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule:
      "Nandrolone Propionate 60mg/ml<br/>Nandrolone Phenylpropionate 60mg/ml<br/>Nandrolone Decanoate 90mg/ml<br/>Nandrolone Laurate 90mg/ml",
    concentration: "300mg/ml",

    volume: "10ml",
    recommendedDosage: "300-900mg/week",
    productDescription:
      "The blend of 4 Nandrolone Esters with a rapid and sustained release for Nandrolone. Relieved muscle pain and speed up the regeneration of muscles recovery.",
    price: 140,
    image: "/products/product_images/Blended_combo_1.webp",
    id: 14,
  },
  {
    manufacturer: "Meditech",
    form: "Oral",
    molecule: "Stanozolol",
    concentration: "10mg",
    volume: "10mg",
    recommendedDosage: "10-60mm/day",
    productDescription:
      "Winstrol is one of the most important hormones. It is used by bodybuilders, use of Winstrol results in extra weight gain, however it is used for drying fat and body sculpting to give the body a beautiful and solid appearance. It's scientific name is Stanzolol, it is not only used by bodybuilders, it is also used by athletes in general, such as runners, weight lifters, and any other sports because it significantly improved performance and makes you more able to tolerate exercise.",
    price: 110,
    image: "/products/product_images/Stanozolol.webp",
    id: 15,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Testosterone Complex",
    concentration: "400mg/ml",
    volume: "10ml",
    recommendedDosage: "400-1200mg/week",
    productDescription:
      "Sustanon Testosterone Mix is the most popular steroid from the injectable steroids range with Sustanon as the trade name. In general, Sustanon is a mixture of four different testosterone components. It includes propionate, phenylpropionate, isocaproate, and decanoate. While they are contained in different proportions, they are able to provide multiple benefits to the user.",
    price: 100,
    image: "/products/product_images/Testosterone_Complex.webp",
    id: 16,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Testosterone Cypionate",
    concentration: "250mg/ml",
    volume: "10ml",
    recommendedDosage: "150-1000mg/week",
    productDescription:
      "Testosterone Cypionate produces a strength gain and a very rapid weight gain, but with a significant water retention and gynecomastia. Your coverage and your raise will be so important. The effects and properties of Testosterone Cypionate are identical in all respects to those of Testosterone Enanthate. The different is that the ester of cypionate is slightly longer and so the effect is also a little longer.",
    price: 98,
    image: "/products/product_images/Testosterone_Cypionate.webp",
    id: 17,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Testosterone Enanthate",
    concentration: "250mg/ml",
    volume: "10ml",
    recommendedDosage: "250-1000mg/week",
    productDescription:
      "Testosterone Enanthate is considered one of the first types of testosterone and is a powerful injectable anabolic steroid, popular and suitable for various purposes. Testosterone Enanthate 250 is acclaimed by users because of its unique advantages such as increased muscle mass, and strength. In addition, it increases the metabolic rate of your body.",
    price: 105,
    image: "/products/product_images/Testosterone_Enanthate.webp",
    id: 18,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule:
      "Testosterone Phenylpropionate 50mg/ml<br/>Boldenone Undecylenate 200mg/ml<br/>Testosterone Cypionate 200mg/ml",
    concentration: "450mg/ml",
    volume: "10ml",
    recommendedDosage: "450-900mg/week",
    productDescription:
      "Meditech created the perfect mix between 3 molecules in a single vial. No more complicated injections to find the best dosage, the vial is ready to be injected with the best compromise in terms of dosage and product quality.",
    price: 145,
    image: "/products/product_images/Blended_combo_2.webp",
    id: 19,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Testosterone Propionate",
    concentration: "100mg/ml",
    volume: "10ml",
    recommendedDosage: "100-400mg/week",
    productDescription:
      "Testosterone Propionate has a very short duration of action, 1 or 2 days only. Like other esters of Testosterone, Testosterone Priopionate provides rapidly important gains in mass and strength, which ensures a denser and better musculature.",
    price: 80,
    image: "/products/product_images/Testosterone_Propionate.webp",
    id: 20,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Testosterone Sustanon",
    concentration: "250mg/ml",
    volume: "10ml",
    recommendedDosage: "500-1000mg/week",
    productDescription:
      "Sustanon 250mg/ml Injectable Vial is a powerful blend of testosterone esters, delivering remarkable gains in muscle mass and strength. This versatile anabolic steroid is well-suited for diverse fitness goals, also enhancing the body's metabolic rate for optimal performance. Embrace the synergy of Sustanon 250 for comprehensive and sustained results in your fitness journey",
    price: 98,
    image: "/products/product_images/Testosterone_Sustanon.webp",
    id: 21,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Trenbolone Acetate",
    concentration: "100mg/ml",
    volume: "10ml",
    recommendedDosage: "200-400mg/week",
    productDescription:
      "The Trenbolone molecule of Parabolan is a great product that does not need to be tested anymore. Parabolan provides muscle mass gain both qualitative and quantitative. It offers impressive vasculature.",
    price: 105,
    image: "/products/product_images/Trenbolone_Acetate.webp",
    id: 22,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule:
      "Trenbolone Acetate 75mg/ml<br/>Drostanolone Propionate 100mg/ml<br/>Testosterone Phenylpropionate 75mg/ml",
    concentration: "250mg/ml",
    volume: "10ml",
    recommendedDosage: "500-1000mg/week",
    productDescription:
      "Meditech created the perfect mix between 3 molecules in a single vial. No more complicated injections to find the best dosage, the vial is ready to be injected with the best compromise in terms of dosage and product quality.",
    price: 170,
    image: "/products/product_images/Blended_combo_3.webp",
    id: 23,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Trenbolone Enanthate",
    concentration: "200mg/ml",
    volume: "10ml",
    recommendedDosage: "200-600mg/week",
    productDescription:
      "Parabolan Trenbolone Enanthate is considered an extremely powerful anabolic steroid with a great ability to improve performance. It is an injectable anabolic steroid generally used for muscle growth. It is unjected once of twice per week. It is used mainly by bodybuilders because it increases body mass and burns fat, accelerating muscle growth immensely. Parabolan has different forms, it is used in natural forms like Acetate and Enanthate, Enanthate is the most common form of Parabolan available. It is known to remain in the body for a short period of time.",
    price: 145,
    image: "/products/product_images/Trenbolone_Enanthate.webp",
    id: 24,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Trenbolone Hexahydrobenzylcarbonate",
    concentration: "150mg/ml",
    volume: "10ml",
    recommendedDosage: "150-600mg/week",
    productDescription:
      "Trenbolone is an injectable anabolic steroid used by bodybuilders and athletes. This steroid is very powerful and builds exceptional muscle mass in a short period of time. Parabolan Trenbolone Hexahydrobenzylcarbonate or simply Trenbolone is very valuable because of its ability to provide rapid muscle growth in a short period of time.",
    price: 180,
    image: "/products/product_images/Trenbolone_Hexahydrobenzylcarbonate.webp",
    id: 25,
  },
  {
    manufacturer: "Meditech",
    form: "Injection",
    molecule: "Winstrol",
    concentration: "100mg/ml",
    volume: "10ml",
    recommendedDosage: "100-500mg/week",
    productDescription:
      "Winstrol Stanozolol is an anabolic steroid typically used for a slimming cycle. While Dianabol or even Anadrol is specifically for a mass-gaining cycle, Winstrol is known worldwide for burning fat.",
    price: 80,
    image: "/products/product_images/Winstrol.webp",
    id: 26,
  },
  {
    manufacturer: "Meditech",
    form: "Oral",
    molecule: "191aa Human Growth Hormone",
    concentration: "  ",
    volume: "",
    recommendedDosage: "",
    productDescription:
      "Human Growth Hormone (HGH), produced by the pituitary gland, regulates vital organ activities and plays a crucial role in health. It earned its name due to its peak secretion during adolescence but has broader functions beyond growth regulation. Also known as somatic troponin, HGH encourages cellular proliferation and has potential cell regeneration capabilities. While it's sought after for enhancing figure, stamina, and muscle growth, synthetic HGH isn't a miracle drug. Endogenous HGH accelerates growth in children and regulates body composition, height, muscle development, bone growth, fluid levels, and",
    price: 80,
    image: "/products/product_images/191aa_Human_Growth_Hormone.webp",
    id: 27,
  },
];
